version: '3'

services:
  web:
    image: marytts-5.2-server
    container_name: marytts-5.2-server
    restart: unless-stopped
    ulimits:
      nproc: 65536
      nofile: 65536
    ports:
      - "59125:59125"


